trigger:
  branches:
    include:
      - prueba-bco  

pool: my_agent_pool

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'  
    displayName: 'Install Node.js'

  - checkout: self  

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run build:test
    displayName: 'npm build'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/dist' 
      TargetFolder: '$(Build.ArtifactStagingDirectory)'  
    displayName: 'Copy build files to artifact staging directory'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
      includeRootFolder: false
      archiveType: 'zip' 
      archiveFile: '$(Build.ArtifactStagingDirectory)/angular-build.zip'  
    displayName: 'Create .zip of build files'

  - publish: '$(Build.ArtifactStagingDirectory)/angular-build.zip'
    artifact: angular-build
    displayName: 'Publish angular build'
